TOPDIR   := $(HOME)/sandbox/c_projects/ray_tracer_challenge
CC_NAMES := color.c $(TOPDIR)/src/common.cc

TOPDIR	:= $(HOME)/sandbox/c_projects/ray_tracer_challenge
C_NAMES	:= color.c

include $(TOPDIR)/makefile.include
